import Head from 'next/head'

const Layout = () => {
    return (
        <Head>
            <title>Next JS - Quizz App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Layout